service: aws-lambda-poc-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    STAGE: ${opt:stage}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: /poc-show

plugins:
  - serverless-offline